### PR TITLE
[#88] fix unrecognised events in parse_event()

### LINKED ISSUE #88: SSE Comments are unrecognised
Lines starting with `:` are comments according to the SSE RFC, yet `parse_event` crashes on them:
```erlang
1> shotgun:parse_event(<<": Comment 1\n: Comment 2\ndata: some data">>).
** exception error: no case clause matching <<": Comment 2">>
     in function  shotgun:'-parse_event/1-fun-0-'/2 (src/shotgun.erl, line 244)
     in call from lists:foldr/3 (lists.erl, line 1274)
```

### PR DESCRIPTION
**Pull request by davecaos**
Fix #88 issue

### CODE REVIEW

File: src/shotgun.erl [hunk 1]
```diff
@@ -247,7 +247,9 @@ parse_event(EventBin) ->
                       <<"id: ", Id/binary>> ->
                           Event#{id => Id};
                       <<"event: ", EventName/binary>> ->
-                          Event#{event => EventName}
+                          Event#{event => EventName};
+                      <<": ", _Comment/binary>> ->
+                          Event#{}
```
Comment (elbrujohalcon) [inline src/shotgun.erl]: no need for `#{}` here

**Comment by elbrujohalcon** [comment]
@davecaos please add .erlang.mk/ to .gitignore
